# Generated by Django 3.0.6 on 2020-06-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0004_auto_20200627_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=32, unique=True)),
                ('last_name', models.CharField(max_length=32, unique=True)),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('phone', models.IntegerField(blank=True, max_length=15, unique=True)),
                ('message', models.TextField(blank=True, max_length=500)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('pend_pay', 'Pendind payment'), ('paid', 'Paid'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('car', models.ManyToManyField(related_name='orders', to='cars.Car')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['last_name', 'email'], name='orders_orde_last_na_5d8e9d_idx'),
        ),
    ]
