# Generated by Django 3.0.6 on 2020-06-27 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dealers', '0003_auto_20200627_1245'),
        ('cars', '0003_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='dealer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dealers.Dealer'),
        ),
        migrations.AddField(
            model_name='property',
            name='car',
            field=models.ManyToManyField(to='cars.Car'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['name'], name='cars_proper_name_9c9042_idx'),
        ),
    ]
